language: java

#jdk:
#  - oraclejdk8

before_install:
  - chmod +x mvnw

after_success:
  - mvn clean test
#  - mvn clean test jacoco:report
#  - mvn clean test jacoco:report coveralls:report


#notifications:
#  email:
#    - yoann.caplain@blackdread.org
